version: '2'
services:
    testapp-app:
        image: testapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://testapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=TestApp
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=testapp-elasticsearch:9300
        ports:
            - 8443:8443
    testapp-mongodb:
        extends:
            file: mongodb.yml
            service: testapp-mongodb
    testapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: testapp-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
